[package]
name = "stat"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = { version = "0.30.9", features = ["serde"] }
itertools = "0.14.0"
nannou = "0.19.0"
nannou_egui = "0.19.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
